services:
  db:
    image: postgres:14-alpine #alpine for lightweight images
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: partyboxes_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: #healthcheck if postgres isnt ready
      test: ["CMD-SHELL", "pg_isready -U postgres -d partyboxes_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/partyboxes_db
      SEED_ADMIN_EMAIL: ${SEED_ADMIN_EMAIL}
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy #calling healthcheck


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:

